name: Video

on:
  #push:
  #  branches: ['main']
  schedule:
    - cron: '20 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 10

    steps:
      
      - name: Checksum
        id: checksum-continue
        run: |
          ip_address=$(curl $XRAY_URL | md5sum)
          wget -O checksum1.txt https://github.com/hello-world-1989/accessible/releases/download/latest/checksum.txt
          github_ip=$(cat checksum1.txt)

          result1="${ip_address// /}"
          result2="${github_ip// /}"
          if [ "$result1" = "$result2" ]; then
              echo "equal"
              echo "continue=n" >> "$GITHUB_OUTPUT"
          else 
              echo "not equal"
              echo "continue=y" >> "$GITHUB_OUTPUT"
              echo "checksum='"$result1"'" >> "$GITHUB_OUTPUT"
          fi
        env:
          XRAY_URL: ${{ secrets.XRAY_URL }}


      - uses: actions/checkout@v4
        if: ${{ steps.checksum-continue.outputs.continue == 'y' }}

      - name: Setup FFmpeg 6.1.0
        if: ${{ steps.checksum-continue.outputs.continue == 'y' }}
        run: |
          # Install NASM and YASM assemblers (required for FFmpeg compilation)
          sudo apt-get update
          sudo apt-get install -y nasm yasm build-essential pkg-config
          
          # Download FFmpeg 6.1.0 source if not present
          if [ ! -f "ffmpeg-6.1.tar.xz" ]; then
            wget https://ffmpeg.org/releases/ffmpeg-6.1.tar.xz
          fi
          
          # Extract and build FFmpeg 6.1.0
          tar -xf ffmpeg-6.1.tar.xz
          cd ffmpeg-6.1
          ./configure --enable-static --disable-shared
          make -j$(nproc)
          sudo make install
          ffmpeg -version
      
      - name: Use Node.js ${{ matrix.node-version }}
        if: ${{ steps.checksum-continue.outputs.continue == 'y' }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Fetch Video
        if: ${{ steps.checksum-continue.outputs.continue == 'y' }}
        run: |
          echo ${{ steps.checksum-continue.outputs.checksum }} > checksum.txt
          git status
          yarn install
          yarn ts-node fetchVideo1.ts
        env:
          IP_CHECK_HOST: ${{ secrets.IP_CHECK_HOST }}
          IP_CHECK_REFERER: ${{ secrets.IP_CHECK_REFERER }}
          IP_CHECK_URL: ${{ secrets.IP_CHECK_URL }}
          GITHUB_TOKEN: ${{ github.token }}
          XRAY_URL: ${{ secrets.XRAY_URL }}

      - name: Release
        if: ${{ steps.checksum-continue.outputs.continue == 'y' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            live/live.mp4
            checksum.txt
          tag_name: latest
          append_body: false

      # - name: Commit files
      #   if: ${{ steps.checksum-continue.outputs.continue == 'y' }}
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "github-actions"
      #     # git config pull.rebase true
      #     # git pull
      #     git status
      #     git add --all
      #     git commit -m "Add videos"
      #     git push

      - name: Youtube Live
        if: ${{ steps.checksum-continue.outputs.continue == 'y' }}
        env:
          LIVE_URL: ${{ secrets.LIVE_URL }}
         # MIRROR_UPDATE_RESTART_WEB_PATH: ${{ secrets.MIRROR_UPDATE_RESTART_WEB_PATH }}
        run: |
          curl $LIVE_URL
         # curl $MIRROR_UPDATE_RESTART_WEB_PATH
